### ISSUE TITLE
Master Issue

### ISSUE THREAD

**Issue by okwme** [folia-app/DoAW#6]
~- [ ] actual NFT interaction:~
  ~- [ ] popup to show price and connect wallet and mint button~
  ~- [ ] when it's on main (not specific NFT) it has custom text cursor "MINT"~
  ~- [ ] when it's on specific NFT there is no click action because that's a specific NFT~
- [ ] Maybe main page is hero animation and mint generates a NFT under it in a grid?
- [ ] Generate GIF
  - [ ] going to need to use node canvas or headless chrome
  - [ ] on server there's no sound, no splash, and no second key that plays so it's a seamless loop, make it land on last color instead of grey
- [ ] Make sounds preload so it plays faster on the phone
  - [ ] could be other optimization needed, research mobile sound speed
- [x] Make width before showing the width of current screen (changes with resize)
- [ ] Make next key immediately play after the current key so there is no gap in between, top data changes as soon as current one ends
